package de.niklaaas.bwshop.handler;

import de.niklaaas.bwshop.methods.ItemBuilder;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class ItemHandler {
    public static ItemStack Blocks = ItemBuilder.ItemWithMaterial(Material.SANDSTONE, 1, "§7» §2Blöcke", true, "Hier findest du Böcke mit denen du dich zu deinen Gegnern bauen kannst!");
    public static ItemStack Ruestung = ItemBuilder.ItemWithMaterial(Material.DIAMOND_CHESTPLATE, 1, "§7» §2Rüstung", true, "Hier findest du Rüstung mit der du dich schützen kannst!");
    public static ItemStack Werkzeug = ItemBuilder.ItemWithMaterial(Material.DIAMOND_PICKAXE, 1, "§7» §2Werkzeug", true, "Hier findest du Werkzeuge mit denen du auch Blöcke zerstört bekommst!");
    public static ItemStack Waffen = ItemBuilder.ItemWithMaterial(Material.DIAMOND_SWORD, 1, "§7» §2Waffen", true, "§fHiermit kannst du deine Gegner im Kampf bezwingen!");
    public static ItemStack Boegen = ItemBuilder.ItemWithMaterial(Material.BOW, 1, "§7» §2Bögen", true, "§fHier findest du Bögen mit denen du aus der Ferne angreifen kannst!");
    public static ItemStack Essen = ItemBuilder.ItemWithMaterial(Material.GRILLED_PORK, 1, "§7» §2Essen", true, "§fHier findest du Nahrung!");
    public static ItemStack Traenke = ItemBuilder.ItemWithShortID(373, 8261, 1, "§7» §2Tränke", true, "§fHier findest du Tränke, die dir einen Vorteil verschaffen können");
    public static ItemStack Special = ItemBuilder.ItemWithMaterial(Material.ENDER_PEARL, 1, "§7» §2Coming Soon", true," ");
    public static ItemStack Emerald = ItemBuilder.ItemWithMaterial(Material.EMERALD, 1, "§7» §2Coming Soon", true, " ");
    public static ItemStack Filler = ItemBuilder.ItemWithShortID(160, 7, 1, " ", false, " ");
    public static ItemStack Sandstone = ItemBuilder.ItemWithMaterial(Material.SANDSTONE, 3, "Sandstein", true, "§fDieser Block ist perfekt für das Bauen eines Wege geeignet!");
    public static ItemStack Stairs = ItemBuilder.ItemWithMaterial(Material.SANDSTONE_STAIRS, 1, "§fStufen", true, "§fEignet sich gut um schnelle Distanzen zu überqueren!");
    public static ItemStack Endstone = ItemBuilder.ItemWithMaterial(Material.ENDER_STONE, 1, "Sandstein", true, "§fDieser Block ist perfekt für das einbauen deines Bettes geeignet!");
    public static ItemStack Glas = ItemBuilder.ItemWithMaterial(Material.GLASS, 1, "§fGlas", true, " ");
    public static ItemStack Glowstone = ItemBuilder.ItemWithMaterial(Material.GLOWSTONE, 1, "§fGlowstone", true, "§fDieser Block eignet sich gut, um dein Bett einzubauen!");
    public static ItemStack Ice = ItemBuilder.ItemWithMaterial(Material.PACKED_ICE, 1, "§fEis", true, "§fEignet sich dafür um schnell von A nach B zu kommen");
    public static ItemStack IronBlock = ItemBuilder.ItemWithMaterial(Material.IRON_BLOCK, 1, "§fEisenblock", true, "§fDieser Block eignet sich sehr gut um dein Bett einzubauen");
    public static ItemStack Bronze1 = ItemBuilder.ItemWithShortID(336, 0, 1, "§cBronze", true, " ");
    public static ItemStack Bronze2 = ItemBuilder.ItemWithShortID(336, 0, 2, "§cBronze", true, " ");
    public static ItemStack Bronze4 = ItemBuilder.ItemWithShortID(336, 0, 4, "§cBronze", true, " ");
    public static ItemStack Bronze7 = ItemBuilder.ItemWithShortID(336, 0, 7, "§cBronze", true, " ");
    public static ItemStack Bronze8 = ItemBuilder.ItemWithShortID(336, 0, 8, "§cBronze",true, " ");
    public static ItemStack Bronze64 = ItemBuilder.ItemWithShortID(336, 0, 64, "§cBronze",true, " ");
    public static ItemStack Ironore1 = ItemBuilder.ItemWithShortID(265, 0, 1, "§7Eisen", true, " ");
    public static ItemStack Ironore2 = ItemBuilder.ItemWithShortID(265, 0, 2, "§7Eisen", true, " ");
    public static ItemStack Ironore3 = ItemBuilder.ItemWithShortID(265, 0, 3, "§7Eisen", true, " ");
    public static ItemStack Ironore4 = ItemBuilder.ItemWithShortID(265, 0, 4, "§7Eisen", true, " ");
    public static ItemStack Ironore5 = ItemBuilder.ItemWithShortID(265, 0, 5, "§7Eisen", true, " ");
    public static ItemStack Ironore7 = ItemBuilder.ItemWithShortID(265, 0, 7, "§7Eisen", true, " ");
    public static ItemStack Ironore8 = ItemBuilder.ItemWithShortID(265, 0, 8, "§7Eisen", true, " ");
    public static ItemStack Ironore10 = ItemBuilder.ItemWithShortID(265, 0, 10, "§7Eisen", true, " ");
    public static ItemStack Ironore64 = ItemBuilder.ItemWithShortID(265, 0, 64, "§7Eisen", true, " ");
    public static ItemStack Goldore1 = ItemBuilder.ItemWithShortID(266, 0, 1, "§6Gold", true, " ");
    public static ItemStack Goldore2 = ItemBuilder.ItemWithShortID(266, 0, 2, "§6Gold", true, " ");
    public static ItemStack Goldore3 = ItemBuilder.ItemWithShortID(266, 0, 3, "§6Gold", true, " ");
    public static ItemStack Goldore7 = ItemBuilder.ItemWithShortID(266, 0, 7, "§6Gold", true, " ");
    public static ItemStack Goldore13 = ItemBuilder.ItemWithShortID(266, 0, 13, "§6Gold", true, " ");
    public static ItemStack Goldore64 = ItemBuilder.ItemWithShortID(266, 0, 64, "§6Gold", true, " ");
    public static ItemStack Goldore5 = ItemBuilder.ItemWithShortID(266, 0, 5, "§6Gold", true, " ");
    public static ItemStack Rod = ItemBuilder.ItemWithMaterial(Material.FISHING_ROD, 1, "§fAngel", true, "§fEine gute Möglichkeit aus geringer Distanz anzugreifen!");
    public static ItemStack FnS = ItemBuilder.ItemWithMaterial(Material.FLINT_AND_STEEL, 1, "§fFeuerzeug", true, "§fBenötigst du um das TNT zu zünden");
    public static ItemStack Pfeil = ItemBuilder.ItemWithMaterial(Material.ARROW, 1, "§fPfeil", true, "§fPfeil und Bogen Utensil!");
    public static ItemStack Apfel = ItemBuilder.ItemWithMaterial(Material.APPLE, 1, "§cApfel", true, "§fNahrung zum Überleben");
    public static ItemStack PorkFleisch = ItemBuilder.ItemWithMaterial(Material.GRILLED_PORK, 1, "§fFleisch", true, "§fNahrung zum Überleben");
    public static ItemStack Kuchen = ItemBuilder.ItemWithMaterial(Material.CAKE, 1, "§fKuchen", true, "§fNahrung zum Überleben");
    public static ItemStack GoldApfel = ItemBuilder.ItemWithMaterial(Material.GOLDEN_APPLE, 1, "§6Goldapfel", true, "§fNahrung zum Überleben");
    public static ItemStack HealTrank = ItemBuilder.ItemWithShortID(373, 16389, 1, "Heiltrank I", true, "§f+2 Herzen (Direktheilung)");
    public static ItemStack HealTrank2 = ItemBuilder.ItemWithShortID(373, 16421, 1, "Heiltrank II", true, "§f3,5Herzen (Direktheilung)");
    public static ItemStack SpeedTrank = ItemBuilder.ItemWithShortID(373, 8194, 1, "Trank der Schnelligkeit", true, "§9Dauer: 3 Minuten");
    public static ItemStack SpeedTrank2 = ItemBuilder.ItemWithShortID(373, 8226, 1, "der Schnelligkeit II",true, "§9Dauer: 1:30 Minuten");
    public static ItemStack InvisTrank = ItemBuilder.ItemWithShortID(373, 8206, 1, "§fTrank der Unsichtbarkeit", true, " ");
}
